FROM docker.elastic.co/beats/elastic-agent:8.19.7

#LABEL com.googleapis.cloudmarketplace.product.service.name="elastic-agent.endpoints.prod-elastic-cloud-billing.cloud.goog"
LABEL com.googleapis.cloudmarketplace.product.service.name="services/Elastic Agent for EKS"
